### ISSUE TITLE
Catalog "Transport" is not working

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [muhammadyusuf-kurbonov/LogiAdmin#20]
Clicking on the Button "Transport"

**Comment by muhammadyusuf-kurbonov** [comment]
Click WHERE? Attach screenshot!

**Comment by Doniyor218** [comment]
![Image](https://user-images.githubusercontent.com/123181341/225385596-ff1c080f-8a0f-4ffb-a1b8-89ab2add0845.jpg)
